version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: yourdbname
      MYSQL_USER: yourdbuser
      MYSQL_PASSWORD: yourdbpassword
      MYSQL_ROOT_PASSWORD: yourdbpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://yourdbuser:yourdbpassword@db:3306/yourdbname

volumes:
  db_data:
